### ISSUE TITLE
Adding L2 Penalty to mimic GAM P-Spline?

### ISSUE THREAD

**Issue by thipokKub** [ZiyaoLi/fast-kan#10]
See [this post](https://www.linkedin.com/posts/ajzhang_stop-the-hype-of-kan-kolmogorov-arnold-activity-7203089908247212032-mq4a/)

KAN use B-spline as an underlying activation. But the default GAM use P-spline. It is possible that the performance difference is because of the L2 penalty on the coefficient weight?

**Comment by ZiyaoLi** [comment]
just personally for me, all implementation with different splines / rbfs does NOT ESSENTIALLY change the performance (accuracy). Arguing some of them being better than others is somehow similar to changing activations in MLPs: are state-of-the-art SiLUs really better than ReLUs? who knows.

btw the robustness / generalizability of KANs against MLPs or other benchmarks are never really studied. Your suggestion of the l2 penalty on coeffs seems reasonable.
