### ISSUE TITLE
Continual Learning Property Preserved?

### ISSUE THREAD

**Issue by yt2639** [ZiyaoLi/fast-kan#11]
Hi thanks for your great work. I am wondering if fast-kan still preserves the continual learning property of the original KAN?

In original KAN, it says:
<img width="710" alt="image" src="https://github.com/ZiyaoLi/fast-kan/assets/46978474/d80e00b2-25db-4b50-8cea-b0717e0ebb26">

Does this property still hold in fast-kan as well?

Thank you for your assistance.

**Comment by ZiyaoLi** [comment]
yes, they would preserve, as the only thing that changed from kan to fastkan is the basis functions.
