### ISSUE TITLE
Forward broken in Fast KAN

### ISSUE THREAD

**Issue by IamShubhamGupto** [ZiyaoLi/fast-kan#2]
logs - [fast-kanmnist.log](https://github.com/ZiyaoLi/fast-kan/files/15270170/fast-kanmnist.log)

Proposed fix
`base = self.base_linear(self.base_activation()(x))` on https://github.com/ZiyaoLi/fast-kan/blob/b64ecad2b81026e49ad992f64374c0d388c98cd4/fastkan/fastkan.py#L59

Device: M1 MacBook Pro
python version: 3.10.14
torch version: 2.3.0
torchvision version: 0.18.0

**Comment by ZiyaoLi** [comment]
Thanks for the feedback. I'm sorry that I was working on the master branch so some of the commits may be buggy. Current version should've fixed this.
