### ISSUE TITLE
Request for Creating Citation

### ISSUE THREAD

**Issue by egmaminta** [ZiyaoLi/fast-kan#4]
Hi! Great work on this one. I've been using FastKAN and efficient-KAN in benchmarking experiments for a mini-project. I would like to cite your project/work, which is why I'm politely requesting a citation (probably in bibtex) for acknowledgment and recognition as well 👍

**Comment by ZiyaoLi** [comment]
Hi @egmaminta ! Thx for your interest! 

Just posted the half-done work on arxiv https://arxiv.org/abs/2405.06721. The full bib is updated on the readme.

**Comment by egmaminta** [comment]
Thank you!
