### ISSUE TITLE
Improvment possible

### ISSUE THREAD

**Issue by chuber11** [ZiyaoLi/fast-kan#6]
Thanks for your implementation.

I noticed that you could speed it up a bit more by merging the division by self.denominator
https://github.com/ZiyaoLi/fast-kan/blob/master/fastkan/fastkan.py#L29
into the layernorm weights
https://github.com/ZiyaoLi/fast-kan/blob/master/fastkan/fastkan.py#L44

Therefore one fewer multiplication/division is needed.

**Comment by ZiyaoLi** [comment]
thanks for the feedback!

doing so would lead to some numerical issues. Let us write the function as f(u)=(exp(-(u-ui)^2)) ^ (1/sigma^2). Then you'll find that the denominator (sigma) leads to non-linearty.

LayerNorm weights can indeed adjust the scale of inputs (u), but more of aligning them to the grids (ui). It cannot adjust the grid grains directly, as denominators are trying to align.

**Comment by chuber11** [comment]
I think you may have misunderstood what exactly I wanted to propose:

Let g = self.grid, d = self.denominator, then we want to compute
y = (x-g)/d=x/d-g/d and then exp(-y**2)

Therefore one can merge the division by d to the layernorm (for the x/d=:x_new part) and to the grid (for the g/d=:g_new part, computed only once at initialization)
and then compute y = x_new - g_new

**Comment by ZiyaoLi** [comment]
Sure that's doable, but I'm particularly worried about the numerical issues. 

Adjusting the grids to g_new would lead to large values. If you take d = h the grid size then the largest deviations of grid values would grow to n_grids, which can grow to hundreds. 

This contradicts with the general assumption that network parameters would better lie in [-2, 2].
