### ISSUE TITLE
why using use_base_update?

### ISSUE THREAD

**Issue by xi-jia** [ZiyaoLi/fast-kan#8]
I noticed that the forward process uses use_base_update = True, wouldn't this incrementally add a KAN on top of a normal mlp/conv? and maybe potentially lead to an unfair comparison?

**Comment by ZiyaoLi** [comment]
You are correct, but that’s exactly what was done in the original KAN by default.

FastKAN makes this optional.

---- Replied Message ----
| From | ***@***.***> |
| Date | 05/24/2024 23:20 |
| To | ZiyaoLi/fast-kan ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [ZiyaoLi/fast-kan] why using use_base_update? (Issue #8) |

I noticed that the forward process uses use_base_update = True, wouldn't this incrementally add a KAN on top of a normal mlp/conv? and maybe potentially lead to an unfair comparison?

**Comment by xi-jia** [comment]
Thank you very much for the clarification and for your efforts in providing the code.
